# MQTT-Modbus Bridge Configuration
# Configuration for bridge between USR-DR164 and Home Assistant

# MQTT Broker Configuration
mqtt:
  broker: "localhost"
  port: 1883
  username: "mqtt"
  password: "mqtt_password"
  client_id: "modbus-bridge"
  
  # USR-DR164 Gateway
  gateway:
    mac: "D4AD20B75646"
    cmd_topic: "D4AD20B75646/cmd"
    data_topic: "D4AD20B75646/data"

# Home Assistant MQTT Discovery Configuration
homeassistant:
  discovery_prefix: "homeassistant"
  device_name: "Energy Meter"
  device_id: "energy_meter_001"
  manufacturer: "Generic"
  model: "Modbus Energy Meter"
  
  # Device status and diagnostics topics
  status_topic: "modbus-bridge/status"          # online/offline status
  diagnostic_topic: "modbus-bridge/diagnostic"  # error codes/messages

# Modbus Device Configuration
modbus:
  slave_id: 11
  poll_interval: 1000       # milliseconds between register set readings
  register_delay: 100       # milliseconds between register reads
  energy_delay: 1000        # milliseconds between energy register reads (kWh meters)
  timeout: 5                # timeout for responses
  republish_interval: 4     # hours between forced republishing of energy sensors

# Modbus Registers with Strategy Pattern
registers:
  voltage:
    name: "Voltage"
    address: 0x2000
    unit: "V"
    device_class: "voltage"
    state_class: "measurement"
    ha_topic: "sensor/energy_meter/voltage"
    min: 100.0      # Minimum acceptable voltage
    max: 300.0      # Maximum acceptable voltage
    
  frequency:
    name: "Frequency"
    address: 0x2020
    unit: "Hz"
    device_class: "frequency"
    state_class: "measurement"
    ha_topic: "sensor/energy_meter/frequency"
    min: 45.0       # Minimum acceptable frequency
    max: 65.0       # Maximum acceptable frequency
    
  current:
    name: "Current"
    address: 0x2002
    unit: "A"
    device_class: "current"
    state_class: "measurement"
    ha_topic: "sensor/energy_meter/current"
    min: 0.0        # Minimum acceptable current
    max: 100.0      # Maximum acceptable current
    
  energy_total:
    name: "Active Energy"
    address: 0x4000
    unit: "kWh"
    device_class: "energy"
    state_class: "total_increasing"
    ha_topic: "sensor/energy_meter/energy_total"
    max_kwh_per_hour: 20.0    # Maximum 20 kWh change per hour
    
  energy_imported:
    name: "Imported Energy"
    address: 0x400A
    unit: "kWh"
    device_class: "energy"
    state_class: "total_increasing"
    ha_topic: "sensor/energy_meter/energy_imported"
    max_kwh_per_hour: 64.0    # Maximum 64 kWh import per hour (high consumption)
    
  energy_exported:
    name: "Exported Energy"
    address: 0x4014
    unit: "kWh"
    device_class: "energy"
    state_class: "total_increasing"
    ha_topic: "sensor/energy_meter/energy_exported"
    max_kwh_per_hour: 3.0     # Maximum 3 kWh export per hour (3kW solar panel)
    
  power_factor:
    name: "Power Factor"
    address: 0x2018
    unit: ""
    device_class: "power_factor"
    state_class: "measurement"
    ha_topic: "sensor/energy_meter/power_factor"
    min: -1.0       # Minimum power factor
    max: 1.0        # Maximum power factor
    
  power_apparent:
    name: "Apparent Power"
    address: 0x2012
    unit: "VA"
    device_class: "apparent_power"
    state_class: "measurement"
    ha_topic: "sensor/energy_meter/power_apparent"
    min: 0.0        # Minimum power
    max: 100000.0   # Maximum 100kVA
    
  power_active:
    name: "Active Power"
    address: 0x2006
    unit: "W"
    device_class: "power"
    state_class: "measurement"
    ha_topic: "sensor/energy_meter/power_active"
    min: -50000.0   # Minimum power (can be negative for export)
    max: 50000.0    # Maximum 50kW

  power_reactive:
    name: "Reactive Power"
    address: 0x0000  # Virtual address - calculated from other values
    unit: "var"
    device_class: "reactive_power"
    state_class: "measurement"
    ha_topic: "sensor/energy_meter/power_reactive"

# Logging
logging:
  level: "info"      # error, warn, info, debug, trace
  file: "/var/log/mqtt-modbus-bridge.log"
  max_size: 100      # MB
  max_age: 30        # days
