# MQTT-Modbus Bridge Configuration Version 2.1
# Example: Multiple Modbus Devices on the Same RTU Bus
# This configuration demonstrates monitoring multiple devices with different slave IDs

version: "2.1"

mqtt:
  broker: "localhost"
  port: 1883
  username: "mqtt"
  password: "mqtt_password"
  client_id: "modbus-bridge"
  gateway:
    mac: "D4AD20B75646"
    cmd_topic: "D4AD20B75646/cmd"
    data_topic: "D4AD20B75646/data"

homeassistant:
  discovery_prefix: "homeassistant"
  device_name: "Energy Monitoring System"
  device_id: "energy_monitoring_001"
  manufacturer: "Custom"
  model: "Multi-Device Modbus RTU Bridge"
  status_topic: "modbus-bridge/status"
  diagnostic_topic: "modbus-bridge/diagnostic"

modbus:
  slave_id: 0              # Not used in V2.1 (devices specify their own)
  poll_interval: 1000      # Default: 1 second
  register_delay: 50
  energy_delay: 5000
  timeout: 5000
  republish_interval: 24

# Multiple devices on the same RTU bus
# Each device has a unique slave_id (1-247)
devices:
  # First Energy Meter - Slave ID 11
  energy_meter_1:
    name: "Energy Meter 1"
    slave_id: 11
    manufacturer: "Chint"
    model: "DTSU666-H"
    enabled: true
    register_groups:
      # Groups can have any name (not limited to "instant" and "energy")
      instant:
        name: "Instant Readings"
        function_code: 0x03  # Read Holding Registers
        start_address: 0x2000
        register_count: 34
        enabled: true
        registers:
          - key: "voltage"
            name: "Voltage"
            offset: 0
            unit: "V"
            device_class: "voltage"
            state_class: "measurement"
            ha_topic: "meter1/voltage"
          - key: "current"
            name: "Current"
            offset: 4
            unit: "A"
            device_class: "current"
            state_class: "measurement"
            ha_topic: "meter1/current"
      
      energy:
        name: "Energy Counters"
        function_code: 0x03
        start_address: 0x4000
        register_count: 22
        enabled: true
        registers:
          - key: "energy_total"
            name: "Total Energy"
            offset: 0
            unit: "kWh"
            device_class: "energy"
            state_class: "total_increasing"
            ha_topic: "meter1/energy_total"
  
  # Second Energy Meter - Slave ID 12
  energy_meter_2:
    name: "Energy Meter 2"
    slave_id: 12          # Different slave ID!
    manufacturer: "Chint"
    model: "DTSU666-H"
    enabled: true
    register_groups:
      instant:
        name: "Instant Readings"
        function_code: 0x03
        start_address: 0x2000
        register_count: 34
        enabled: true
        registers:
          - key: "voltage"
            name: "Voltage"
            offset: 0
            unit: "V"
            device_class: "voltage"
            state_class: "measurement"
            ha_topic: "meter2/voltage"
          - key: "current"
            name: "Current"
            offset: 4
            unit: "A"
            device_class: "current"
            state_class: "measurement"
            ha_topic: "meter2/current"
      
      energy:
        name: "Energy Counters"
        function_code: 0x03
        start_address: 0x4000
        register_count: 22
        enabled: true
        registers:
          - key: "energy_total"
            name: "Total Energy"
            offset: 0
            unit: "kWh"
            device_class: "energy"
            state_class: "total_increasing"
            ha_topic: "meter2/energy_total"
  
  # Solar Inverter - Slave ID 20
  inverter_1:
    name: "Solar Inverter"
    slave_id: 20          # Different slave ID and device type!
    manufacturer: "Growatt"
    model: "MIN 3000TL-X"
    enabled: true
    poll_interval: 2000   # Override: poll every 2 seconds
    register_groups:
      # Custom group name (not "instant" or "energy")
      status:
        name: "Inverter Status"
        function_code: 0x04  # Read Input Registers (different from meters!)
        start_address: 0x0000
        register_count: 30
        enabled: true
        registers:
          - key: "pv_voltage"
            name: "PV Voltage"
            offset: 0
            unit: "V"
            device_class: "voltage"
            state_class: "measurement"
            ha_topic: "inverter/pv_voltage"
          - key: "pv_power"
            name: "PV Power"
            offset: 8
            unit: "W"
            device_class: "power"
            state_class: "measurement"
            ha_topic: "inverter/pv_power"
      
      # Another custom group name
      production:
        name: "Energy Production"
        function_code: 0x04
        start_address: 0x0100
        register_count: 10
        enabled: true
        registers:
          - key: "energy_today"
            name: "Energy Today"
            offset: 0
            unit: "kWh"
            device_class: "energy"
            state_class: "total_increasing"
            ha_topic: "inverter/energy_today"

logging:
  level: "info"
