# MQTT-Modbus Bridge Configuration Version 2.1
version: "2.1"

mqtt:
  broker: "localhost"
  port: 1883
  username: "mqtt"
  password: "mqtt_password"
  client_id: "modbus-bridge"
  keep_alive: 60              # MQTT keep alive interval in seconds (default: 60)
  heartbeat_interval: 20      # Status heartbeat interval in seconds (default: 20)
  gateway:
    mac: "D4AD20B75646"
    cmd_topic: "D4AD20B75646/cmd"
    data_topic: "D4AD20B75646/data"

homeassistant:
  discovery_prefix: "homeassistant"
  status_topic: "modbus-bridge/status"
  diagnostic_topic: "modbus-bridge/diagnostic"
  
  # Per-device diagnostic sensors configuration
  device_diagnostics:
    enabled: true                    # Enable diagnostic sensor for each device (default: true)
    publish_on_state_change: true    # Publish immediately when device state changes (default: true)
    
    # Publish intervals per device state (in seconds)
    intervals:
      operational: 60                # Device working perfectly (default: 60s)
      warning: 30                    # Device has minor issues (default: 30s)
      error: 5                       # Device has serious errors - fast updates for debugging (default: 5s)
      offline: 60                    # Device not responding (default: 60s)
    
    # Thresholds for determining device state
    thresholds:
      warning_success_rate: 90.0        # Success rate below this triggers warning state (default: 90.0%)
      error_success_rate: 80.0          # Success rate below this triggers error state (default: 80.0%)
      warning_consecutive_errors: 3     # Consecutive errors to trigger warning (default: 3)
      error_consecutive_errors: 5       # Consecutive errors to trigger error (default: 5)
      offline_timeout: 30               # Seconds without response to trigger offline (default: 30s)

modbus:
  poll_interval: 1000
  register_delay: 50
  energy_delay: 5000
  timeout: 5000
  republish_interval: 24

logging:
  level: "info"

devices:
  # CHINT DDSU666-H Single-Phase Energy Meter
  # See docs/DDSU666-H.md for detailed documentation
  energy_meter_mains:
    metadata:
      name: "Energy Meter Mains"
      manufacturer: "Chint Electric Co."
      model: "DDSU666-H Single-Phase Meter"
      enabled: true
    
    rtu:
      slave_id: 11
      poll_interval: 1000
    
    homeassistant:
      device_id: "energy_meter_mains"
      manufacturer: "Chint Electric Co."
      model: "DDSU666-H Single-Phase Energy Meter"
    
    modbus:
      register_groups:
        instant:
          name: "Instant Measurements"
          function_code: 0x03
          start_address: 0x2000
          register_count: 34
          enabled: true
          registers:
            - key: "voltage"
              name: "Voltage"
              offset: 0
              unit: "V"
              device_class: "voltage"
              state_class: "measurement"
              min: 100.0
              max: 300.0

            - key: "current"
              name: "Current"
              offset: 4
              unit: "A"
              device_class: "current"
              state_class: "measurement"
              min: 0.0
              max: 100.0

            - key: "power_active"
              name: "Active Power"
              offset: 12
              unit: "W"
              scale_factor: 1000
              device_class: "power"
              state_class: "measurement"
              min: -50000.0
              max: 50000.0

            - key: "power_apparent"
              name: "Apparent Power"
              offset: 36
              unit: "VA"
              scale_factor: 1000
              device_class: "apparent_power"
              state_class: "measurement"
              min: 0.0
              max: 100000.0

            - key: "power_factor"
              name: "Power Factor"
              offset: 48
              unit: ""
              device_class: "power_factor"
              state_class: "measurement"
              min: -1.0
              max: 1.0

            - key: "frequency"
              name: "Frequency"
              offset: 64
              unit: "Hz"
              device_class: "frequency"
              state_class: "measurement"
              min: 45.0
              max: 65.0

        energy:
          name: "Energy Counters"
          function_code: 0x03
          start_address: 0x4000
          register_count: 22
          enabled: true
          registers:
            - key: "energy_total"
              name: "Total Active Energy"
              offset: 0
              unit: "kWh"
              device_class: "energy"
              state_class: "total_increasing"
              max_kwh_per_hour: 20.0

            - key: "energy_imported"
              name: "Imported Energy"
              offset: 20
              unit: "kWh"
              device_class: "energy"
              state_class: "total_increasing"
              max_kwh_per_hour: 64.0

            - key: "energy_exported"
              name: "Exported Energy"
              offset: 40
              unit: "kWh"
              device_class: "energy"
              state_class: "total_increasing"
              max_kwh_per_hour: 3.0

    # Calculated values - computed after all Modbus reads complete
    calculated_values:
      - key: "power_reactive"
        name: "Reactive Power"
        unit: "var"
        formula: "sqrt(power_apparent^2 - power_active^2)"
        scale_factor: 1.0  # Result is already in var (VA and W input units)
        device_class: "reactive_power"
        state_class: "measurement"

  # CHINT DDSU666 Single-Phase Energy Meter (Simplified Model)
  # See docs/DDSU666.md for detailed documentation
  energy_meter_lights:
    metadata:
      name: "Energy Meter Lights"
      manufacturer: "Chint Electric Co."
      model: "DDSU666 Single-Phase Meter"
      enabled: true
    
    rtu:
      slave_id: 1                     # Different slave ID from main meter
      poll_interval: 1000
    
    homeassistant:
      device_id: "energy_meter_lights"
      manufacturer: "Chint Electric Co."
      model: "DDSU666 Single-Phase Energy Meter"
    
    modbus:
      register_groups:
        instant:
          name: "Instant Measurements"
          function_code: 0x03
          start_address: 0x2000
          register_count: 16
          enabled: true
          registers:
            - key: "voltage"
              name: "Voltage"
              offset: 0
              unit: "V"
              device_class: "voltage"
              state_class: "measurement"
              min: 100.0
              max: 300.0

            - key: "current"
              name: "Current"
              offset: 4
              unit: "A"
              device_class: "current"
              state_class: "measurement"
              min: 0.0
              max: 100.0

            - key: "power_active"
              name: "Active Power"
              offset: 8
              unit: "W"
              scale_factor: 1000.0    # DDSU666 reports in kW, convert to W
              device_class: "power"
              state_class: "measurement"
              min: -50000.0
              max: 50000.0

            - key: "power_reactive"
              name: "Reactive Power"
              offset: 12
              unit: "var"
              scale_factor: 1000.0    # DDSU666 reports in kvar, convert to var
              device_class: "reactive_power"
              state_class: "measurement"
              min: -50000.0
              max: 50000.0

            - key: "power_factor"
              name: "Power Factor"
              offset: 20
              unit: ""
              device_class: "power_factor"
              state_class: "measurement"
              min: -1.0
              max: 1.0

            - key: "frequency"
              name: "Frequency"
              offset: 28
              unit: "Hz"
              device_class: "frequency"
              state_class: "measurement"
              min: 45.0
              max: 65.0

        energy:
          name: "Energy Counter"
          function_code: 0x03
          start_address: 0x4000
          register_count: 12
          enabled: true
          registers:
            - key: "energy_imported"
              name: "Imported Active Energy"
              offset: 0
              unit: "kWh"
              device_class: "energy"
              state_class: "total_increasing"
              max_kwh_per_hour: 20.0

            - key: "energy_exported"
              name: "Exported Energy (Reverse)"
              offset: 20
              unit: "kWh"
              device_class: "energy"
              state_class: "total_increasing"
              max_kwh_per_hour: 3.0

    # Calculated values - computed after all Modbus reads complete
    calculated_values:
      - key: "power_apparent"
        name: "Apparent Power"
        unit: "VA"
        formula: "sqrt(power_active^2 + power_reactive^2)"
        device_class: "apparent_power"
        state_class: "measurement"
      - key: "energy_total"
        name: "Total Active Energy"
        unit: "kWh"
        formula: "abs(energy_imported - energy_exported)"
        device_class: "energy"
        state_class: "total_increasing"

  # Example: Growatt Solar Inverter
  # Demonstrates configuration for different device types
  inverter_1:
    metadata:
      name: "Solar Inverter"
      manufacturer: "Growatt"
      model: "MIN 3000TL-X"
      enabled: true
    rtu:
      slave_id: 20
      poll_interval: 2000
    homeassistant:
      device_id: "growatt_inverter_1"
      manufacturer: "Growatt New Energy"
      model: "MIN 3000TL-X Grid-Tied Inverter"
    modbus:
      register_groups:
        status:
          name: "Inverter Status"
          function_code: 0x04
          start_address: 0x0000
          register_count: 30
          enabled: true
          registers:
            - key: "pv_voltage"
              name: "PV Voltage"
              offset: 0
              unit: "V"
              device_class: "voltage"
              state_class: "measurement"
