# MQTT-Modbus Bridge Configuration Version 2.1
version: "2.1"

mqtt:
  broker: "localhost"
  port: 1883
  username: "mqtt"
  password: "mqtt_password"
  client_id: "modbus-bridge"
  gateway:
    mac: "D4AD20B75646"
    cmd_topic: "D4AD20B75646/cmd"
    data_topic: "D4AD20B75646/data"

homeassistant:
  discovery_prefix: "homeassistant"
  status_topic: "modbus-bridge/status"
  diagnostic_topic: "modbus-bridge/diagnostic"

modbus:
  poll_interval: 1000
  register_delay: 50
  energy_delay: 5000
  timeout: 5000
  republish_interval: 24

logging:
  level: "info"

devices:
  energy_meter_1:
    metadata:
      name: "Energy Meter 1"
      manufacturer: "Chint"
      model: "DDSU666-H"
      enabled: true
    
    rtu:
      slave_id: 11
      poll_interval: 1000
    
    homeassistant:
      device_id: "chint_meter_1"
      manufacturer: "Chint Electric"
      model: "DDSU666-H Three-Phase Energy Meter"
    
    modbus:
      register_groups:
        # Instant measurements group - reads all real-time values in single command
        instant:
          name: "Instant Measurements"
          function_code: 0x03         # Read Holding Registers
          start_address: 0x2000       # Starting register address
          register_count: 34          # Total registers to read (0x22)
          enabled: true
          registers:
            - key: "voltage"
              name: "Voltage"
              offset: 0               # 0x2000 - 0x2000 = 0 (bytes 0-3)
              unit: "V"
              device_class: "voltage"
              state_class: "measurement"
              min: 100.0              # Minimum valid voltage
              max: 300.0              # Maximum valid voltage

            - key: "current"
              name: "Current"
              offset: 4               # 0x2002 - 0x2000 = 2 registers = 4 bytes
              unit: "A"
              device_class: "current"
              state_class: "measurement"
              min: 0.0
              max: 100.0              # Maximum rated current

            - key: "power_active"
              name: "Active Power"
              offset: 12              # 0x2006 - 0x2000 = 6 registers = 12 bytes
              unit: "W"
              device_class: "power"
              state_class: "measurement"
              min: -50000.0           # Allow negative (export)
              max: 50000.0

            - key: "power_apparent"
              name: "Apparent Power"
              offset: 36              # 0x2012 - 0x2000 = 18 registers = 36 bytes
              unit: "VA"
              device_class: "apparent_power"
              state_class: "measurement"
              min: 0.0
              max: 100000.0

            - key: "power_reactive"
              name: "Reactive Power"
              offset: 0               # Virtual register - calculated from active and apparent
              unit: "var"
              device_class: "reactive_power"
              state_class: "measurement"

            - key: "power_factor"
              name: "Power Factor"
              offset: 48              # 0x2018 - 0x2000 = 24 registers = 48 bytes
              unit: ""
              device_class: "power_factor"
              state_class: "measurement"
              min: -1.0
              max: 1.0

            - key: "frequency"
              name: "Frequency"
              offset: 64              # 0x2020 - 0x2000 = 32 registers = 64 bytes
              unit: "Hz"
              device_class: "frequency"
              state_class: "measurement"
              min: 45.0
              max: 65.0

        # Energy counters group - reads cumulative energy values
        energy:
          name: "Energy Counters"
          function_code: 0x03
          start_address: 0x4000
          register_count: 22          # Number of registers (0x16)
          enabled: true
          registers:
            - key: "energy_total"
              name: "Total Active Energy"
              offset: 0               # 0x4000 - 0x4000 = 0
              unit: "kWh"
              device_class: "energy"
              state_class: "total_increasing"
              max_kwh_per_hour: 20.0  # Maximum expected change per hour

            - key: "energy_imported"
              name: "Imported Energy"
              offset: 20              # 0x400A - 0x4000 = 10 registers = 20 bytes
              unit: "kWh"
              device_class: "energy"
              state_class: "total_increasing"
              max_kwh_per_hour: 64.0

            - key: "energy_exported"
              name: "Exported Energy"
              offset: 40              # 0x4014 - 0x4000 = 20 registers = 40 bytes
              unit: "kWh"
              device_class: "energy"
              state_class: "total_increasing"
              max_kwh_per_hour: 3.0
  
  energy_meter_2:
    metadata:
      name: "Energy Meter 2"
      manufacturer: "Chint"
      model: "DTSU666-H"
      enabled: true
    
    rtu:
      slave_id: 12
    
    # homeassistant section omitted - will use device key "energy_meter_2" as device_id
    # and metadata values for manufacturer/model
    
    modbus:
      register_groups:
        instant:
          name: "Instant Measurements"
          function_code: 0x03
          start_address: 0x2000
          register_count: 34
          enabled: true
          registers:
            - key: "voltage"
              name: "Voltage"
              offset: 0
              unit: "V"
              device_class: "voltage"
              state_class: "measurement"
              min: 100.0
              max: 300.0

            - key: "current"
              name: "Current"
              offset: 4
              unit: "A"
              device_class: "current"
              state_class: "measurement"
              min: 0.0
              max: 100.0

            - key: "power_active"
              name: "Active Power"
              offset: 12
              unit: "W"
              device_class: "power"
              state_class: "measurement"
              min: -50000.0
              max: 50000.0

            - key: "frequency"
              name: "Frequency"
              offset: 64
              unit: "Hz"
              device_class: "frequency"
              state_class: "measurement"
              min: 45.0
              max: 65.0

        energy:
          name: "Energy Counters"
          function_code: 0x03
          start_address: 0x4000
          register_count: 22
          enabled: true
          registers:
            - key: "energy_total"
              name: "Total Active Energy"
              offset: 0
              unit: "kWh"
              device_class: "energy"
              state_class: "total_increasing"
              max_kwh_per_hour: 20.0
  
  inverter_1:
    metadata:
      name: "Solar Inverter"
      manufacturer: "Growatt"
      model: "MIN 3000TL-X"
      enabled: true
    rtu:
      slave_id: 20
      poll_interval: 2000
    homeassistant:
      device_id: "growatt_inverter_1"
      manufacturer: "Growatt New Energy"
      model: "MIN 3000TL-X Grid-Tied Inverter"
    modbus:
      register_groups:
        status:
          name: "Inverter Status"
          function_code: 0x04
          start_address: 0x0000
          register_count: 30
          enabled: true
          registers:
            - key: "pv_voltage"
              name: "PV Voltage"
              offset: 0
              unit: "V"
              device_class: "voltage"
              state_class: "measurement"
