version: "2.1"

mqtt:
  broker: "localhost"
  port: 1883
  username: ""
  password: ""
  client_id: "mqtt-modbus-bridge"
  retry_delay: 5000
  gateway:
    publish_online: true
    online_topic: "homeassistant/bridge/status"
    online_payload: "online"
    offline_payload: "offline"
    mac: "AA:BB:CC:DD:EE:FF"

homeassistant:
  discovery_prefix: "homeassistant"
  device_id: "modbus_gateway"
  status_topic: "homeassistant/bridge/status"
  diagnostic_topic: "homeassistant/bridge/diagnostics"
  device_name: "MQTT-Modbus Gateway"
  device_model: "v1.0"
  device_manufacturer: "Custom"

modbus:
  device: "/dev/ttyUSB0"
  baud_rate: 9600
  data_bits: 8
  parity: "N"
  stop_bits: 1
  poll_interval: 1000
  energy_delay: 60000
  timeout: 500

logging:
  level: "info"
  format: "text"

devices:
  test_meter:
    metadata:
      name: "Test Meter"
      manufacturer: "Test"
      model: "Test-001"
      enabled: true

    rtu:
      slave_id: 1

    modbus:
      register_groups:
        group1:
          name: "Measurements"
          function_code: 0x03
          start_address: 0x2000
          register_count: 10
          enabled: true
          registers:
            - key: ""  # EMPTY KEY - should fail validation
              name: "Voltage"
              offset: 0
              unit: "V"
              device_class: "voltage"
              state_class: "measurement"
